
SELECT * FROM BRANCH;
SELECT * FROM STAFF;
SELECT * FROM PROPERTY;
SELECT * FROM RENTER;
SELECT * FROM OWNER;
SELECT * FROM VIEWING;


--q1 
--viewing and renter

-- SELECT RENTER.FName, RENTER.LName, RENTER.Address
-- FROM RENTER, VIEWING
-- WHERE VIEWING.RenterNo = RENTER.RenterNo;

--q2

-- SELECT PROPERTY.Type, PROPERTY.Rooms
-- FROM PROPERTY, STAFF
-- WHERE STAFF.Job = 'Manager';

--q3

-- SELECT OWNER.FName, OWNER.LName
-- FROM OWNER, PROPERTY
-- WHERE (OWNER.OwnerNo = PROPERTY.OwnerNo) AND (PROPERTY.Type = 'Apartment');


--q4

-- SELECT STAFF.FName, STAFF.LName, STAFF.BranchNo
-- FROM STAFF, PROPERTY
-- WHERE (STAFF.BranchNo = PROPERTY.BranchNo) AND PROPERTY.City = 'Cork';






--q5

SELECT RENTER.FName, RENTER.LName
FROM RENTER, PROPERTY, VIEWING
WHERE (VIEWING.RenterNo = RENTER.RenterNo) AND (VIEWING.PropertyNo = PROPERTY.PropertyNo) AND PROPERTY.Rooms >=3;

--q6

-- SELECT STAFF.FName, STAFF.LName
-- FROM STAFF, PROPERTY, OWNER
-- WHERE (STAFF.StaffNo = PROPERTY.StaffNo) AND (PROPERTY.OwnerNo = OWNER.OwnerNo) AND (OWNER.FName = 'Woody' AND OWNER.LName = 'Allen');